sudo: false
cache: packages

matrix:
  include:

  # R for travis: https://docs.travis-ci.com/user/languages/r
  - language: r
    before_install: cd src/R_code/tmvariants/
    cache: packages

  - language: python
    python: 3.4
    before_install: 
      - pip install --upgrade pip
      - cd src/python_code/
    install: 
    #      - pip install --upgrade setuptools
      - pip install -r requirements.txt
    script: python -m unittest

